# required for building jre_lwjgl3glfw with Java 8 while using plugins in app_pojavlauncher that require Java 11
org.gradle.configureondemand=true

android.useAndroidX=true
android.enableJetifier=true
# Increase Gradle daemon RAM allocation
org.gradle.jvmargs=-Xmx4096M

# Ensure localizations aren't ruined
android.bundle.language.enableSplit=false

# We still use R for switch cases, so keep these options so they work
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.defaults.buildfeatures.resvalues=true

# Android studio added it idk
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
org.gradle.parallel=true
org.gradle.caching=true
